/*
 * 模块概述
 * ========
 * 本文件实现了LoRaWAN基站的关键字CRC生成工具。这是一个用于
 * 构建阶段的辅助程序，用于生成JSON解析器中使用的关键字哈希
 * 值，提高字符串比较的效率。通过预计算常用关键字的CRC值，
 * 该工具减少了运行时的字符串比较操作，提升了处理性能。
 * 
 * 文件功能
 * ========
 * 本工具主要实现以下功能：
 * - 计算输入关键字的CRC哈希值
 * - 检测哈希冲突并报告
 * - 生成C语言头文件格式的宏定义
 * - 标准化关键字标识符格式
 * 
 * 主要组件
 * ========
 * 1. CRC计算引擎
 *    - 自定义多项式哈希函数
 *    - 哈希值规范化处理
 *    - 冲突检测机制
 * 
 * 2. 代码生成器
 *    - 宏定义生成
 *    - 标识符规范化
 *    - 格式化输出
 * 
 * 3. 辅助功能
 *    - 命令行参数处理
 *    - 错误报告和处理
 *    - 特殊字符转换
 * 
 * 算法细节
 * ========
 * 1. CRC计算
 *    - 使用两个质数(257和65537)作为多项式系数
 *    - 对字符串中每个字符依次更新哈希值
 *    - 处理特殊情况如哈希值为0
 * 
 * 2. 冲突处理
 *    - 检测不同字符串产生相同哈希值的情况
 *    - 在发现冲突时终止程序并报告
 *    - 通过哈希参数调整减少冲突概率
 * 
 * 3. 标识符生成
 *    - 将非字母数字字符转换为下划线
 *    - 保持关键字的可读性
 *    - 确保生成的标识符符合C语言命名规范
 * 
 * 使用方法
 * ========
 * 1. 直接使用
 *    - 运行程序并提供关键字列表作为命令行参数
 *    - 程序输出宏定义代码到标准输出
 * 
 * 2. 构建集成
 *    - 作为构建过程的一部分自动运行
 *    - 生成的头文件由JSON解析器包含
 * 
 * 注意事项
 * ========
 * 1. 构建依赖
 *    - 本程序仅在CFG_prog_genkwcrcs定义时编译
 *    - 依赖uj.h头文件定义的类型
 * 
 * 2. 性能影响
 *    - 生成的CRC值直接影响JSON解析性能
 *    - 精心选择的哈希参数对减少冲突至关重要
 * 
 * 3. 安全属性
 *    - 哈希值不能为0（通过FINISH_CRC宏确保）
 *    - 不同字符串不能产生相同哈希值（冲突检测）
 *    - 标识符必须符合C语言命名规范（非字母数字字符转换）
 */

/*
 * --- Revised 3-Clause BSD License ---
 * Copyright Semtech Corporation 2022. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *
 *     * Redistributions of source code must retain the above copyright notice,
 *       this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright notice,
 *       this list of conditions and the following disclaimer in the documentation
 *       and/or other materials provided with the distribution.
 *     * Neither the name of the Semtech corporation nor the names of its
 *       contributors may be used to endorse or promote products derived from this
 *       software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL SEMTECH CORPORATION. BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
 * LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#if defined(CFG_prog_genkwcrcs)

#include <stdio.h>
#include "uj.h"

#define P1 257
#define P2 65537
#define SC (32-8)

#define FINISH_CRC(crc)    X((crc) ? (crc) : 1)
#define UPDATE_CRC(crc, c) X((((crc)>>SC)*P2) ^ ((crc)*P1) ^ ((c)&0x7F))
#define STR(expr) CAT(XXX,expr)
#define STR2(p) #p
#define CAT(p, ...) STR2(p ##__VA_ARGS__)

ujcrc_t X(ujcrc_t x) {
    return x;
}

ujcrc_t calcCRC(const char* s) {
    ujcrc_t crc = 0;
    int c;
    while( (c=*s++) ) {
        crc = UPDATE_CRC(crc,c);
    }
    return FINISH_CRC(crc);
}

int main (int argc, char** argv) {
    argv++;
    argc--;
    ujcrc_t crcs[argc];
    for( int i=0; i<argc; i++ ) {
        ujcrc_t crc = calcCRC(argv[i]);
        crcs[i] = crc;
        for( int j=i-1; j>=0; j-- ) {
            if( crcs[j] == crc && strcmp(argv[j], argv[i]) != 0 ) {
                fprintf(stderr, "Collision: %s(0x%X) vs %s(0x%X)\n",
                        argv[i], crc, argv[j], crcs[j]);
                exit(1);
            }
        }
    }
    printf("// Auto generated by genkwcrcs - DO NOT CHANGE!\n");
    printf("#define UJ_UPDATE_CRC(crc,c) %s\n", 4+STR(UPDATE_CRC(crc,c)));
    printf("#define UJ_FINISH_CRC(crc)   %s\n", 4+STR(FINISH_CRC(crc)));
    for( int i=0; i<argc; i++ ) {
        char ident[256];
        int cj = 0;
        for( cj=0; argv[i][cj]; cj++ ) {
            char c = argv[i][cj];
            ident[cj] = (c>='0' && c<='9') || (c>='a' && c<='z') || (c>='A' && c<='Z') ? c : '_';
        }
        ident[cj] = 0;
        printf("#define J_%-20s ((ujcrc_t)(0x%08X))\n", ident, crcs[i]);
    }
    return 0;
}

#endif // defined(CFG_prog_genkwcrcs)
